# Generated by Django 5.2.8 on 2025-11-26 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_testimonys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='audio',
        ),
    ]
