# Generated by Django 5.2.8 on 2025-11-26 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_announcement_audio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sermon',
            old_name='date',
            new_name='Date',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='file',
        ),
    ]
